#############################
# Configuration for GAR
# Версия от 19.04.2023
#
#############################

version: '3.9'

services:
  # fias-gar-node:
  #   build: .
  #   env_file: .env
  #   depends_on:
  #     - db
  #   ports:
  #   - 3001:3001
  #   - 3080:3080
  #   - 3081:3081
  #   container_name: ${PROJECT_NAME}_service
  #   links:
  #     - db:db
  #   volumes:
  #     - ./data:/GarBase/data
  #   networks:
  #     - app-network
  db:
    image: mariadb:10.6
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_USER: ${DB_ROOT}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    container_name: ${PROJECT_NAME}_db
    ports:
        - "3306:3306"
    # networks:
    #   - app-network
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ./data/mysql/initdb:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    env_file: .env
    environment:
      - PMA_ARBITRARY=1
    container_name: ${PROJECT_NAME}_adminDB
    # networks:
    #   - app-network
    depends_on:
      - db
# networks:
#   app-network:
#     driver: bridge