#############################
# Configuration for GAR
# Версия от 19.04.2023
#
#############################

version: '3.9'

services:
############################################-Реализация фронт end-############################### 
    # nevatom_cloud_front:
    #   # Действия при перезапуске 
    #   # restart: always
    #   image: kolyaz/nevatom_cloud_front
    #   volumes:
    #     - pwa:/pwa/

    #   # Команда, которую нужно запустить после создания образа.
    #   # Следующая команда означает запуск "python ./server.py".
    #   # command: node server.js

    #   # Если мы хотим обратиться к серверу с нашего компьютера (находясь за пределами контейнера),
    #   # мы должны организовать перенаправление этого порта на порт компьютера.
    #   # Сделать это нам поможет ключевое слово 'ports'.
    #   ports:
    #     - 3001:3001
    #     - 3080:3080
    #   container_name: ${PROJECT_NAME}_front
################################-Реализация бэк end-############################################
    # nevatom_cloud_back:
    #   restart: always
    #   # build: nevatom_cloud_back/
    #   image: kolyaz/nevatom_cloud_back
    #   volumes:
    #     - pwa:/Nevatom_cloud_back/client/pwa/
    #     - ./data/certbot/conf:/etc/letsencrypt
    #     - ./data/certbot/lib:/var/lib/letsencrypt
    #     - ./data/certbot/www:/var/www/certbot
    #   ports:
    #     - 3001:3001
    #     - 3080:3080
    #     - 3081:3081
    #   # Ключевое слово 'depends_on' позволяет указывать, должен ли сервис,
    #   # прежде чем запуститься, ждать, когда будут готовы к работе другие сервисы.
    #   depends_on:
    #     - mysql
    #     - nevatom_cloud_front
    #   container_name: ${PROJECT_NAME}_backend
    #   networks: 
    #     - app-network
  ##############################-MySQL-#####################################################
    mysql:
      image: mariadb:10.6
      restart: always
      env_file: .env
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PW}
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      ports:
        - "3306:3306"
      container_name: ${PROJECT_NAME}_mysql
      volumes:
        - ./data/mysql:/var/lib/mysql
        - ./data/mysql/initdb:/docker-entrypoint-initdb.d
      networks: 
        - app-network
  ########################################-DataBase Manager-#####################################################
    # adminer:
    #   image: adminer
    #   container_name: ${PROJECT_NAME}_adminer
    #   environment:
    #     ADMINER_DEFAULT_SERVER: mysql
    #   restart: always
    #   ports:
    #     - 8080:8080
    #   depends_on:
    #       - mysql
    phpmyadmin:
      image: phpmyadmin
      container_name: ${PROJECT_NAME}_phpmyadmin
      restart: always
      ports:
        - 8080:80
      environment:
        # - PMA_ARBITRARY=1
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      networks: 
        - app-network
      depends_on:
          - mysql
  ##########################################-NGINX-###############################################################    
    # nginx:
    #     image: nginx:alpine
    #     volumes:
    #         - pwa:/var/www/html
    #         - ./nginx-conf:/etc/nginx/conf.d
    #         - ./data/certbot/conf:/etc/letsencrypt
    #         - ./data/certbot/lib:/var/lib/letsencrypt
    #         - ./data/certbot/www:/var/www/certbot
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     restart: always
    #     depends_on:
    #     #     - nevatom_cloud_front
    #         - nevatom_cloud_back
    #     container_name: ${PROJECT_NAME}_nginx
    #     networks: 
    #         - app-network
#########################################################################################################################
volumes:
  pwa:
  # certbot-etc:
  # certbot-var:
  # certbot-www:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
networks:
  app-network:
    driver: bridge
# services:
#   db:
#     image: mariadb:10.6
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: notSecureChangeMe

#   phpmyadmin:
#     image: phpmyadmin
#     restart: always
#     ports:
#       - 8080:80
#     environment:
#       - PMA_ARBITRARY=1